apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-ingress
  namespace: api
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /api/user
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/user
        pathType: Prefix
        backend:
          service:
            name: userprofile
            port:
              number: 80
