apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sqlpassword
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: 651ef4c5-80a7-4fa0-a7e7-edc62202ade8   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: AKSVAULTINSTANCE        # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: secret1
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
    tenantId: 2d2c69da-5a38-4e2c-91c8-44cec6954548 # The tenant ID of the key vault
