kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-user-access
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-user-full-access
subjects:
- kind: Group
  namespace: web
  name: 450000de-35fd-4481-ad30-836977c6aa03